### ISSUE TITLE
Example* functions should only be in the tests (and documentation).

### ISSUE THREAD

**Issue by dchapes** [bartmeuris/progressio#1]
Functions such as `ExampleWriter` in [example.go](https://github.com/bartmeuris/progressio/blob/master/examples.go#L73) should only exist in tests and godoc. I.e. put them in [`*_test.go` files](https://golang.org/pkg/testing/#hdr-Examples).

**Comment by bartmeuris** [comment]
good catch, was a last minute change, should be fixed now :)
